version: '3.8'

services:
  db:
    image: postgres:15
    container_name: recommendation_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recommendation_system
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
